### ISSUE TITLE
Som en användare vill jag kunna logga in med mitt lokala konto.

### ISSUE THREAD

**Issue by helgaRee** [ECProjectGroup5/accountProvider#2]
### **Tasks**

- [ ] Bygga ett inloggningssformulär.
       - Skapade fält för epost och password.

- [ ] Varje inputfält ska valideras i frontend
      - Epost ska minst vara enligt följande kombination [xx@xx.xx](mailto:xx@xx.xx).
      - Password ska innehålla 8-15 tecken, minst 1 gemen, minst 1 versal, minst 1 siffra, minst 1 specialtecken.

- [ ] Varje inputfält ska valideras i backend
        - Kontroll om e-postadressen finns i systemet.
        - Kontroll password matchar med eposten.
        - Lyckat redirect till shoppen.
         - Vid misslyckad inloggning så nollställs formuläret.
       
### **ACCEPTANSKRITERIER**

Validering av obligatoriska fält
 - Om något fält (email, lösenord) inte är ifyllt eller felaktigt ifyllt, ska ett felmeddelande visas och formuläret ska rensas.

Felmeddelande vid felaktig inmatning
 - Det ska visas ett tydligt meddelande om något av formulärdatat är icke korrekt ifyllt (t.ex. "Incorrect Credentials").
 
Vid lyckad inloggning
 - Efter att användaren framgångsrikt kunnat loggat in, skickas användaren till startsidan.

### **TESTFALLSBESKRIVNING**

**Beskrivning** Testa att alla obligatoriska fält (email och lösenord) är ifyllda korrekt.
Om formuläret ej är ifyllt korrekt, ska formuläret rensas och ges felmeddelande om att fel uppgifter fyllts i,
och skickas tillbaka till start page(?)
för att försöka igen pånytt.

  **Förutsättning** Att användaren har öppnat sidan till inloggningsformuläret för att logga in.

  **steg** 
   1. Lämna fältet "Email" tomt och försök logga in.
   2. Lämna fältet "lösenord" tomt och försök logga in.
   3. Ange felaktigt format för "Email" och försök att logga in.
   4. Ange felaktigt lösenord till en redan skapad användare, och försök logga in.

   **Förväntat resultat**
    1. När fältet "Email" är tomt, ska ett felmeddelande visas: "You must enter an Email".
    2. När fältet "Password" är tomt, ska ett felmeddelande visas: "You must enter a password".
    3. Om felaktig inmatning av "Email" eller "Password" ska ett felmeddelande visas: "Invalid credentials".

###  **Activity Diagram:** 
|Frontend|
@startuml

start

:User visits start page;
:User enters email and password, presses login button;

:Validate email and password in frontend;
if (Form data is valid?) then (yes)
  #palegreen:Frontend validation successful;
else (no)
  #pink:Frontend validation failed;
  :Reset form;
  :Redirect to start page;
  stop
endif

|Backend|
:Validate email in backend;
if (User exists in database?) then (yes)
  :Check password;
  if (Password matches?) then (yes)
    #palegreen:Login user;
  else (no)
    #pink:Incorrect password;
    :Reset form;
    :Redirect to start page;
    stop
  endif
else (no)
  #pink:Email not registered;
  :Reset form;
  :Redirect to start page;
  stop
endif

@enduml

![Image](https://github.com/user-attachments/assets/2420fb8c-3a3e-4eac-8222-25d770cf0103)

###  **Sequence Diagram:** 
![Image](https://github.com/user-attachments/assets/a6e08e53-3ab1-4dc3-a440-9d78054c632b)
