### ISSUE TITLE
Som en användare vill jag kunna logga in till mitt lokala konto

### ISSUE THREAD

**Issue by helgaRee** [ECProjectGroup5/accountProvider#3]
### **Tasks**

- [x] Bygga ett inloggningsformulär
       -  Skapa fält för epost och lösenord

- [x] Varje inputfält ska valideras i frontend
      - Epost ska minst vara enligt följande kombination xx@xx.xx.
      - Lösenord ska innehålla 8-15 tecken, minst en bokstav i upper case, minst 1 siffra, minst 1 bokstav i
        lower case, minst 1 specialtecken.

- [x] Varje inputfält ska valideras i backend
     - Kontroll om e-postadressen finns i systemet.
     - Kontroll password matchar med eposten.
     - Lyckat redirect till shoppen.
     - Vid misslyckad inloggning så nollställs formuläret.

### **Acceptanskriterier**
**Validering av obligatoriska fält**
- Om något fält (epost eller lösenord) inte är ifyllt eller felaktigt ifyllt, ska ett felmeddelande visas och formuläret ska rensas.
**Felmeddelande vid felaktig inmatning**
- Det ska visas ett tydligt meddelande om något av formulärdatat är icke korrekt ifyllt (te.x. "Incorrect Credentials").
**Vid lyckad inloggning**
- Användaren skickas till startsidan vid lyckad inloggning.

### **Testfallsbeskrivning**

**Beskrivning**
Testa att alla obligatoriska fält (epost och lösenord) är ifyllda korrekt.
Om formuläret ej är ifyllt korrekt, ska formuläret rensas och ges felmeddelande om att fel uppgifter fyllts i. 

**Förutsättning**
Att användaren har öppnat sidan till inloggningsformuläret för att logga in.

**Steg**
1. Lämna fältet "Email" tomt och försök att logga in.
2. Lämna fältet "Password" tomt och försök att logga in.
3. Ange felaktigt format för "Email" och försök att logga in.
4. Ange felaktigt format för "Password" och försök att logga in.

**Förväntat resultat**

1.  När fältet "Email" är tomt, ska ett felmeddelande visas: "You must enter an email".
2. När fältet "Password" är tomt, ska ett felmeddelande visas: "You must enter your password".
3. Om felaktig inmatning av "Email" eller "Password" ska ett felmeddelande visas: "Invalid Credentials".

### **Aktivitetsdiagram**
![Image](https://github.com/user-attachments/assets/3bc80614-f6cb-459d-8a3e-8e28ef93eafc)

### **Sekvensdiagram**
![Image](https://github.com/user-attachments/assets/68a01213-6ca7-45a7-93c5-bd261875f847)
